### ISSUE TITLE
"File name too long" error if prompt exceeds valid filename length

### ISSUE THREAD

**Issue by Sam-Izdat** [basujindal/stable-diffusion#2]
If your prompt is too long, this happens:

`OSError: [Errno 36] File name too long`

Pretty easy fix. [Here](https://github.com/basujindal/stable-diffusion/blob/6d5bd47931efca43b5aa2198e6a6698438dfb781/optimizedSD/optimized_txt2img.py#L157), we can just change:

```python
sample_path = os.path.join(outpath, "samples", "_".join(opt.prompt.split()) )
```

to 

```python
sample_path = os.path.join(outpath, "samples", "_".join(opt.prompt.split())[0:50] )
```

... or something similar.

**Comment by basujindal** [comment]
Thank you for reporting the issue. I have used your suggestion and fixed the code. Will push the code in some time.

**Comment by thezveroboy** [comment]
there are still an error on Windows because with long prompt you can't save the result for this path:

Traceback (most recent call last):
  File "optimizedSD/optimized_txt2img.py", line 158, in <module>
    os.makedirs(sample_path, exist_ok=True)
  File "C:\Users\cotton\miniconda3\envs\ldm\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] System can't find the path ...
